### PR TITLE
add bot user token to UI project

### PR DESCRIPTION
**Pull request by swaroopar**

### CODE REVIEW

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
secret has been added.

**Comment by swaroopar** [comment]
@netomi thank you for this. But it looks like there is an issue with the secret added. I get the below error - 

https://github.com/eclipse-xpanse/xpanse-ui/actions/runs/6367789925/job/17286646289

It could be probably happening if the token does not have an expiry date. 

Could you please help here?

**Comment by netomi** [comment]
I double checked the permissions of the token, it has only public_repo as scope enabled, so I am not sure what this token is being used for. I checked the existing workflows, and it is only used to checkout, something that you could also do with the GITHUB_TOKEN that is generated during the workflow.

Regarding the use in the release-it job: the workflow already requests write permissions for content and packages, so passing just secrets.GITHUB_TOKEN as env variable to the job should make it work imho. I would suggest to clean the use of the 3208 token for all workflows, use the generic GITHUB_TOKEN and after that we can remove the secrets for all repos.

**Comment by swaroopar** [comment]
@netomi Thanks for checking. In the past, we used the used this special token to allow writes to `main` branch which is otherwise blocked. (I forgot to add this extra config for the xpanse-ui project). 

https://github.com/eclipse-xpanse/.eclipsefdn/blob/main/otterdog/eclipse-xpanse.jsonnet#L138

Do you mean that this is not required anymore?

**Comment by netomi** [comment]
Looking at the workflows and the uses of the Token i believe you could just use the GITHUB_TOKEN instead.

**Comment by swaroopar** [comment]
@netomi thank you. That's even cleaner. Then I will give it a try and get back to you in case of any further support needed from you.

**Comment by swaroopar** [comment]
@netomi unfortunately it fails with the 'protected branch' error - https://github.com/eclipse-xpanse/xpanse-ui/actions/runs/6378550799/job/17309330714

in the 'xpanse' and 'terraform-boot' repos, we used the 'BOT_GITHUB_TOKEN' to solve this issue.

Should we add the `bypass_pull_request_allowances` for the GITHUB_TOKEN user?

**Comment by netomi** [comment]
ok, I missed that there is a branch protection rule on the project to prevent direct pushes.

So you will need to use a bot token to bypass as I found no other solution to allow the default token to bypass a branch protection rule.

The token api-token-3388 already has the permissions that you need, I will update the repo secret for the xpanse-ui repo and once you have reverted your workflow to the original it should work imho.

Sorry for the inconvenience, I will continue to look how to bypass branch protection rules with the default GITHUB TOKEN.

**Comment by netomi** [comment]
actually there is already an org secret:

```
    orgs.newOrgSecret('BOT_GITHUB_DOCKER_TOKEN') {
      value: "pass:bots/technology.xpanse/github.com/api-token-3388",
    },
```

so you could use that already.

**Comment by swaroopar** [comment]
@netomi this token was used for only uploading artifacts to GitHub packages. Can this token also write to repos? Also, can you please confirm if this token also belongs to 'eclipse-xpanse-bot'  user ?
If yes, I will open a PR to allow pushes to main branch for this user.

**Comment by netomi** [comment]
The scopes for the tokens are as follows:

image

This does not match with the comments in the referenced help desk tickets, which probably stirred that confusion.
From the existing scopes, the 3388 token should be able to push to the repo and write to packages.

The 3208 token should be able to push to the repo, but not being able to write to packages, which was the original problem afaict.

**Comment by swaroopar** [comment]
@netomi We are already using token 3208 in other repos for reading and writing to repos. But when I used it on xpanse-ui repo, even the checkout failed. We do not try to use it for writing to packages.

**Pull request merged**
